version: 2.1

jobs:
  ubuntu1804-python2:
    docker:
      - image: stbtester/circleci:ubuntu1804-python2
    environment:
      PYTHON_VERSION: 2.7
    steps:
      - checkout
      - test

  ubuntu1804-python3:
    docker:
      - image: stbtester/circleci:ubuntu1804-python3
    environment:
      PYTHON_VERSION: 3.6
    steps:
      - checkout
      - test

commands:
  test:
    steps:
      - run:
          name: make check
          environment:
            LANG: en_GB.UTF-8
            SHELL: /bin/bash
            TERM: xterm
          command: |
            tesseract --version
            pylint --version
            make enable_virtual_stb=no parallel=xargs check

workflows:
  test_all:
    jobs:
      - ubuntu1804-python2
      - ubuntu1804-python3
